# Top section (see also "_includes/sections/top.md")
photo_credit: Kur Organic Superfoods

# How it works section
journey:
  title: "Here's how it works..."

  steps:
  - title: "Create your profile"
    icon: "long-arrow-right"
    description: "Based on your profile we will introduce you to a host of great products we know you´ll love to try."
    img_path: "user-journey/TS_step1.png"
  - title: "Get credit and choose away"
    icon: "long-arrow-right"
    description: "Each month you get credit to spend on new products to explore. Choose away - it’s on us!"
    img_path: "user-journey/TS_step2.png"
  - title: "Try your products"
    icon: "long-arrow-right"
    description: "Place your order and get your products delivered right to your doorstep."
    img_path: "user-journey/TS_step3.png"
  - title: "Share your thoughts!"
    icon: "check"
    description: "We thrive on feedback, and so do the folks who make the stuff.
Share your thoughts and we'll give you more credit to spend!"
    img_path: "user-journey/TS_step4.png"

#Product categories
product_categories:
  title: "And this is just the beginning…"
  sub_title: "We're continually adding new things for you to try!"
  categories:
  - title: "Snacks"
    css_class: "product-sample7"
  - title: "Beverages"
    css_class: "product-sample8"
  - title: "Health"
    css_class: "product-sample5"
  - title: "Bath &amp; Body"
    css_class: "product-sample3"


#Videos
videos:
  title: "Check out some of our inspirations"
  items:
  - title: "Sustainia Award Finalists 2014"
    img_path: "videos/video1.png"
  - title: "The Kur Bar<br>– Simply Scandinavian"
    img_path: "videos/video2.png"
  - title: "Sustainia - 100 Great Ideas"
    img_path: "videos/video3.png"
  - title: "The Organic Effect"
    img_path: "videos/video4.png"


#SIGNUP FORM (BOTTOM)
section_signup:
  title: "Join us and feel good about your choices!"
  sub_title: "Be the change. Help manufacturers of responsibly made products.<br> Your feedback is invaluable."
  button_text_desktop: "SIGN UP"
  button_text_mobile: "SIGN UP"

# Site settings
site_name: "Trysome"
title: "Try before you buy! Go ahead, TrySome!"
email: "rfk@gotrysome.com"
description: > # this means to ignore newlines until next symbol
  Trysome gives you responsibly produced high quality food and beauty products
og_description: >
  Trysome gives you responsibly produced high quality food and beauty products. It´s easy and FREE. So if you care about the food you consume and the products you slather on our skin, come join us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gotrysome.com" # the base hostname & protocol for your site
twitter_username: trysome
github_username:  trysome

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass

gems: ['kramdown', 'jekyll-redirect-from']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
